language: java

stages:
  - mavenclean
  - pushondocker


jobs:
  include:
    - stage: mavenclean
      name: mavenclean
      script: mvn clean verify --file ./simple-api/pom.xml org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=evrardkey
      if: branch = dev

    - stage: pushondocker
      name: docker
      script:
        - docker login -u $DOCKER_USER -p $DOCKER_PWD
        - docker build -t $DOCKER_USER/devopstp_2:database database
        - docker build -t $DOCKER_USER/devopstp_2:httpd httpd
        - docker build -t $DOCKER_USER/devopstp_2:simple-api simple-api
        - docker build -t $DOCKER_USER/devopstp_2:front front
        - docker push $DOCKER_USER/devopstp_2:database
        - docker push $DOCKER_USER/devopstp_2:httpd
        - docker push $DOCKER_USER/devopstp_2:simple-api
        - docker push $DOCKER_USER/devopstp_2:front
      if: branch = dev

cache:
  directories:
    - $HOME/.m2

service:
  - docker

addons:
  sonarcloud:
    organization: "devopevrard"
    token: "$SONARCLOUD_TOKEN"







