language: java
script:
  - cd ./simple-api/
  - mvn clean verify org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=evrardkey
  - cd ..

#  - mvn clean verify --file ./simple-api/pom.xml
  - docker login -u $DOCKER_USER -p $DOCKER_PWD

  - docker build -t $DOCKER_USER/super-release:database database
  - docker build -t $DOCKER_USER/super-release:simple-api simple-api
  - docker build -t $DOCKER_USER/super-release:httpd httpd

  - docker push $DOCKER_USER/super-release:database
  - docker push $DOCKER_USER/super-release:httpd
  - docker push $DOCKER_USER/super-release:simple-api


cache:
  directories:
    - $HOME/.m2

service:
  - docker

addons:
  sonarcloud:
    organization: "devopevrard"
    token: "$SONARCLOUD_TOKEN"

